export default {
  title: 'Subscription to balance', adminIntro: 'Let users convert active subscriptions they purchased into account balance.', userIntro: 'Preview your credit. Confirming credits your balance and revokes the subscription.',
  enabled: 'Enable subscription conversion for users', enabledHint: 'Enabling shows the user menu and allows conversion. Disabling hides the entry and blocks conversion requests.', save: 'Save settings', saved: 'Settings saved', saving: 'Saving…', refresh: 'Refresh', loading: 'Loading…', retry: 'Retry',
  formulaTitle: 'Conversion rules', formula: 'Credit = purchase price × (remaining time ratio × 50% + remaining quota ratio × 50%)',
  timeRule: 'Remaining time ratio = remaining seconds ÷ purchased seconds.', quotaRule: 'Total quota = monthly quota × purchased days ÷ 30. Remaining quota ratio = (total quota − lifetime usage) ÷ total quota, with a minimum of 0.',
  priceRule: 'Uses the price saved in completed purchase orders, including renewals in the current subscription term. Current plan prices and payment fees are excluded.',
  exampleTitle: 'Example', example: '$30 purchase, 50% of time and 80% of quota remaining: $30 × (50% × 50% + 80% × 50%) = $19.50.',
  precision: 'Settlement uses time and recorded usage at confirmation. Credit is rounded down to 6 decimals in the account currency, USD.',
  eligibility: 'Eligible subscriptions', eligibleHint: 'Active subscriptions with verified purchase orders and monthly quotas qualify. Admin grants, redeem codes, mixed free extensions, and orders under refund do not qualify.',
  historyHint: 'Missing usage history or unverifiable terms display an explanation. Missing usage is never treated as zero. Converted subscriptions cannot be restored and related orders cannot be refunded.',
  closed: 'Subscription conversion is unavailable', closedHint: 'Your conversion estimates will appear when the administrator enables this feature.', activeTitle: 'Active subscriptions', empty: 'No active subscriptions', emptyHint: 'Active subscriptions you purchase will appear here.',
  group: 'Subscription', expiry: 'Expires', price: 'Purchase price', remainingTime: 'Time remaining', remainingQuota: 'Quota remaining', monthlyQuota: 'Monthly quota', totalQuota: 'Total quota', usedQuota: 'Lifetime usage', estimate: 'Estimated credit', days: '{days} days', orders: 'Purchase orders',
  convert: 'Convert to balance', unavailable: 'Unavailable', details: 'Calculation details', timeRatio: 'Time remaining ratio', quotaRatio: 'Quota remaining ratio',
  confirmTitle: 'Confirm subscription conversion', confirmHint: 'This immediately revokes “{name}”. Keys bound to this group lose its subscription benefits; future requests follow the group’s billing rules.', acknowledge: 'I understand that the subscription cannot be restored and related orders cannot be refunded.', confirm: 'Confirm conversion', cancel: 'Cancel', converting: 'Converting…', success: 'Converted successfully. ${amount} credited.', stale: 'This is an estimate. The final credit is calculated when you confirm.',
  history: 'Conversion history', historyLimit: 'Showing the latest 100 records. Full records are retained on the server.', historyEmpty: 'No conversions yet', convertedAt: 'Converted', credited: 'Credit received', converted: 'Converted to balance',
  reasons: { not_purchased: 'Only verified purchases qualify; purchase source could not be verified', inactive: 'Subscription expired or has not started', mixed_term: 'Term includes adjustments outside purchases', usage_incomplete: 'Usage history is incomplete', unsupported_quota: 'Requires a monthly quota without daily or weekly limits', order_unavailable: 'A related order is incomplete, refunded, or under refund', too_small: 'Credit is less than 0.000001 USD', pending_requests: 'A request or usage charge is still settling. Refresh and try again shortly.', unsettled_usage: 'A request was not settled successfully. Contact an administrator to reconcile it.' },
  failed: 'Could not complete the request. Please try again.'
}
